### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by xxTAT** [XDcat/GerpHelper#2]
Hello, I am having trouble using gerp++KRT_patch. After make. I ran the test code./gerpcol -t NP_000006.2.blast.dnd -f NP_000006.2.blast. aln.fa-e NP_000006.2-v-j-a. But there are many caveats. The contents are as follows.
_______________________________________________________________________________________________________________________________
gpp-gerpcol
Fri Oct 18 09:54:58 PM CST 2024
Neutral rate computed from tree file = 4.59197
Neutral rate after rescaling = 4.59197

Processing NP_000006.2.blast.aln.fa, output will be written to NP_000006.2.blast.aln.fa.rates
Nucleotide frequencies:  A = 0.235252, C = 0.0867093, G = 0.348259, T = 0.32978
Alignment species NP_000006. not found in tree and therefore ignored.
Alignment species UniRef50_P1844 not found in tree and therefore ignored.
Alignment species UniRef50_P1391 not found in tree and therefore ignored.
Alignment species UniRef50_P5029 not found in tree and therefore ignored.
Alignment species UniRef50_A0A835NPR not found in tree and therefore ignored.
Alignment species UniRef50_Q7YRG not found in tree and therefore ignored.
Alignment species UniRef50_A0A7L3LZ4 not found in tree and therefore ignored.
Alignment species UniRef50_A0A7M4EES not found in tree and therefore ignored.
Alignment species UniRef50_P1124 not found in tree and therefore ignored.
Alignment species UniRef50_A0A315W0K not found in tree and therefore ignored.
Alignment species UniRef50_F7GEM not found in tree and therefore ignored.
Alignment species UniRef50_E3TFT not found in tree and therefore ignored.
Alignment species UniRef50_A0A151NM7 not found in tree and therefore ignored.
Alignment species UniRef50_A0A1U7CIP not found in tree and therefore ignored.
Alignment species UniRef50_A0A3Q2NWL not found in tree and therefore ignored.
Alignment species UniRef50_V9KYW not found in tree and therefore ignored.
Alignment species UniRef50_A7HT3 not found in tree and therefore ignored.
Alignment species UniRef50_A0A444TX5 not found in tree and therefore ignored.
Alignment species UniRef50_H3AI1 not found in tree and therefore ignored.
Alignment species UniRef50_A0A6J4UIK not found in tree and therefore ignored.
Alignment species UniRef50_A0A517SAE not found in tree and therefore ignored.
Tree species UniRef50_A0A315W0K9 not present in this alignment and therefore ignored.
Tree species UniRef50_E3TFT8 not present in this alignment and therefore ignored.
Tree species UniRef50_V9KYW8 not present in this alignment and therefore ignored.
Tree species UniRef50_F7GEM4 not present in this alignment and therefore ignored.
Tree species UniRef50_P50298 not present in this alignment and therefore ignored.
Tree species UniRef50_P18440 not present in this alignment and therefore ignored.
Tree species NP_000006.2 not present in this alignment and therefore ignored.
Tree species UniRef50_P11245 not present in this alignment and therefore ignored.
Tree species UniRef50_Q7YRG5 not present in this alignment and therefore ignored.
Tree species UniRef50_A0A151NM70 not present in this alignment and therefore ignored.
Tree species UniRef50_A0A835NPR5 not present in this alignment and therefore ignored.
Tree species UniRef50_A0A7M4EES2 not present in this alignment and therefore ignored.
Tree species UniRef50_P13914 not present in this alignment and therefore ignored.
Tree species UniRef50_A0A7L3LZ45 not present in this alignment and therefore ignored.
Tree species UniRef50_A0A6J4UIK7 not present in this alignment and therefore ignored.
Tree species UniRef50_A0A3Q2NWL2 not present in this alignment and therefore ignored.
Tree species UniRef50_A0A444TX58 not present in this alignment and therefore ignored.
Tree species UniRef50_H3AI17 not present in this alignment and therefore ignored.
Tree species UniRef50_A7HT34 not present in this alignment and therefore ignored.
Tree species UniRef50_A0A1U7CIP0 not present in this alignment and therefore ignored.
Tree species UniRef50_A0A517SAE6 not present in this alignment and therefore ignored.
Processing alignment of 901 positions, maximum neutral rate is 4.59197
Segmentation fault (core dumped)

If you can help, I would appreciate it.

**Comment by xxTAT** [comment]
I've solved the problem

**Comment by willright28** [comment]
Hi @xxTAT ，
I met the same question as yours. It seems the gerpcol miss the last letter of sample's name when it read the tree. Could you share how you sovled this problem? 

Thanks!

**Comment by xxTAT** [comment]
Hi willright28，
I reinstalled the gerp tool with conda and there were no errors. I think the problem is the result of incorrect compilation, because I made an error during compilation.I hope it was helpful.
Best.
